# 1. Python Basic 

#### 1.1 Data Types

In [2]:
type('this is string')

str

In [3]:
type(1)

int

In [4]:
type(0.555)

float

In [5]:
type(True)

bool

In [6]:
type(False)

bool

#### 1.2 Math Operatoins



In [7]:
# Sum
1+2

3

In [8]:
# Divide
9/3

3.0

In [9]:
#Divide %
9%3

0

In [10]:
#Substract

90-900


-810

#### 1.3 Python  Build in Functions


In [11]:
print('Hi')


print(type)



print(len('List String'))

Hi
<class 'type'>
11


In [12]:
# space and new line for strin values in python
print("\n hi\t Python")


 hi	 Python


#### 1.4 Text Slicing 


In [13]:
sample='Sample'

In [14]:
#Frist char
sample[0]

'S'

In [15]:
# Last char

sample[-1]

'e'

In [16]:
# Print all indexis
print(sample[::])
print(sample[:])

Sample
Sample


In [17]:
#Slicing

s='MyNameISHassan'

s[-7:-11:-3] #[First Index , Second Index, Step]
#First Index +( - or + step) to 
# (+ or -(second index) - 1 )
#[1,3,4,6,7,8,9] 
#list

'Sm'

In [18]:
# Get the second element from the end of the list to second element at the begining of the list
s[-2:-len(s):-1]

'assaHSIemaNy'

In [19]:
s[-1:-len(s):-1]

'nassaHSIemaNy'

##### 1.4.1 Text Method


In [27]:
#remove every space before and after the string  

s='   string    '
s.strip()

'string'

In [28]:
#remove every - before and after the string  

s='--------string------------'
s.strip('-')

'string'

In [29]:
#remove every - from the right 
s='--------string------------'
s.rstrip('-')

'--------string'

In [30]:
#remove every - from the left 

s='--------string------------'
s.lstrip('-')

'string------------'

In [32]:
# split the string 
s='soso,sososos,ososo'

s.split(',')



['soso', 'sososos', 'ososo']

In [36]:
# split with specifc numbers 
s='soso,sososos,ososo,ososo,ososo,ososo,ososo,ososo'

s.split(',',4)

['soso', 'sososos', 'ososo', 'ososo', 'ososo,ososo,ososo,ososo']

In [41]:
# count repted string in word
s='soso,sososos,ososo'

s.count('so')

7

In [40]:
# count reapted string in part of word
s='soso,sososos,ososo'

s.count('so',0,10)

4

#### 1.4 List Tuple Set 


In [20]:
['lis','231','4234']*2

['lis', '231', '4234', 'lis', '231', '4234']

> the list can not use any math opertions like sum or supstract int form each element in the list

In [21]:
# merge two list
l1=[1,2,3,4]
l2=[1,5,6,7,8]
l3=l1+l2
print(l3)

#or use append
l3.append(10)
print(l3)


[1, 2, 3, 4, 1, 5, 6, 7, 8]
[1, 2, 3, 4, 1, 5, 6, 7, 8, 10]


In [33]:
### Unpacking list

x,y,z=[2,1,3]

print(x)
print(z)
print(y)

# multi varible can be equal to the same thing
n=v=m=[1,4,5]
print(v)
print(n)
print(m)

2
3
1
[1, 4, 5]
[1, 4, 5]
[1, 4, 5]


In [22]:
# can update value of index
l3[0]=6
print(l3)

[6, 2, 3, 4, 1, 5, 6, 7, 8, 10]


In [23]:
# tuple the same as list  , but can not update value of index or append into it
t=(1,23,34,4,3)
t[0]=8

TypeError: 'tuple' object does not support item assignment

In [ ]:
# must any value between ()  follow by , to be tuple

print(type((1)))

print(type((1,)))

<class 'int'>
<class 'tuple'>


In [26]:
# set , sort the numbers and dose not accept any repated value  ,no slicing using it is index, can not update it is value ,sort the numbers fisrt then str value 

se={7}

se.add(4)

se.add(8)
se.add('p')
se.add('a')

In [24]:
# dictionar have key and value 

dic={'ee':5}


# update value of key
dic['ee']=9

In [25]:
#remove key and vlaue and save the removed value of the key in variable
n=dic.pop('ee')
n

9

#### 1.5 If Condition


In [1]:
a=20
b=19
j=40

if a>b or a>j:
    print(a)

20


In [9]:
num1=int(input('pls input a number '))
num2=int(input('pls input a number '))

operation=input('pls input select on of the followig \n 1- sum \n 2-supstract (-) \n 3- multi (*) \n 4- divide (/)')


if operation == '+':
    print(num1+num2)


elif operation == '-':
    print(num1-num2)



elif operation == '*':
    print(num1*num2)

elif operation == '/':
    print(num1/num2)

else:

    operation=input('pls input a valid choice  \n one of the followig \n 1- sum \n 2-supstract (-) \n 3- multi (*) \n 4- divide (/)')



#### 1. 6  While Loop


In [15]:
i =1


while i < 9 :
    print(i)

    i+=1

    if i ==3 :
        break

1
2


In [19]:
i =0


while i < 9 :
    i+=1
    if i ==3 :
        continue
    print(i)

1
2
4
5
6
7
8
9


#### 1.6 Function


In [43]:
def print_str(fnam):
    print(fnam+"  i am not feeling good")


print_str('hassan')
print_str('ali')
print_str('khamis')

hassan  i am not feeling good
ali  i am not feeling good
khamis  i am not feeling good


In [52]:
# *x means function_name( will accept alot of paramters not specif ones)
#and to get any value of the input ,all paramter that was input to the function  will have index , to get it must called by it is index inside the function 
def print_str(*x):
    print(x[0]+"  i am not feeling good")

In [53]:
print_str('Hassan','Ali','Khamis','HI')


Hassan  i am not feeling good


In [54]:
def print_str(*x):
    print(x[3]+"  i am not feeling good")

print_str('Hassan','Ali','Khamis','HI')


HI  i am not feeling good


In [2]:
x = 88
# x global variable
def print_global():

    return x

print_global()

88

In [10]:

# x global variable
def print_global():

    global x
    #nonlocal  x --> the same as glopal but needs to be in nested function
    x=99

    return x

print_global()



99

In [11]:
print(f'THIS IS X={x}')

THIS IS X=99


In [55]:
# *x means function_name( will accept alot of paramters not specif ones)
#and to get any value of the input ,all paramter that was input to the function will have key , to get it must called by it is name inside the function 
def print_str(**x):
    print(x['first']+"  i am not feeling good")
print_str(first='Hassan',last='Ali',mid='Khamis',mid_last='HI',test_last='Jack')


Hassan  i am not feeling good


In [56]:
print_str(first='Hassan',last='Ali',mid='Khamis',mid_last='HI',test_last='Jack')


Hassan  i am not feeling good


In [57]:
def print_str(**x):
    print(x['Lol']+"  i am not feeling good")
print_str(first='Hassan',last='Ali',mid='Khamis',mid_last='HI',test_last='Jack',Lol='212')

212  i am not feeling good


In [61]:
# lambda function 

name_checker=lambda num : 'even' if num%2==0 else 'odd'

name_checker(8)

'even'

In [66]:
# map each  elemnt in list and do something on it 
def add(x):
    return x+x

list(map(str,range(1,40)))

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39']

In [72]:
# filter will retun only the value in list  of true condtion   
def add(x):

        return x ==8


list(filter(add,range(1,10)))


[8]

#### 1.7 Classes


In [12]:
class dog ():
    num_dog=0 # variable  inside  the class will update each time we assigne the class to an object
    def __init__(self,name,age) :
        dog.num_dog+=1
        self.name=name
        self.age=age
    
print(f'num of dogs=={dog.num_dog}')
dog1=dog('j',5)
dog2=dog('Jakc',5)
dog3=dog('KOko',7)
dog4=dog('LoLO',7)
print(f'num of dogs=={dog.num_dog}')





num of dogs==0
num of dogs==4


In [13]:
class Pitbull(dog):
    def run(self):
        print(f'RUN {self.name} RUN {self.name} RUN RUN !!! ')

n=Pitbull('Geffery',90)

In [14]:
n.run()

RUN Geffery RUN Geffery RUN RUN !!! 


In [47]:
class Encapsulation():
    def __init__(self,name,age):
        self.name=name
        self.__age=age   # make only this attr private inside the class
    def P(self):
        return self.name +"  " +str(self.__age)

In [48]:
con=Encapsulation('G',6)

print(con.__age())

AttributeError: 'Encapsulation' object has no attribute '__age'

In [49]:
# print local attr from iside of the class and print
print(con._Encapsulation__age
)

6


In [50]:
con.P()

'G  6'

#### 1.8 Ex About Function


In [85]:
def sum_row(v1,v2):
    if len(v1) == len (v2):
        l=[v1[i]+v2[i] for i  in  range(len(v1))]
        return(l)
    else:
        print('Unvalid Shape')


def sum_mat(mat1,mat2):
    l=[]
    for i in range(len(mat1)):
        l.append(sum_row(mat1[i],mat2[i]))
    return l

mat1=[[1,2,1],[2,1,7]]
mat2=[[1,3,1],[3,1,1]]
sum_mat(mat1,mat2)




[[2, 5, 2], [5, 2, 8]]

In [89]:
[[1,2,1],[2,1,7]]

[[1, 2, 1], [2, 1, 7]]

In [94]:
mat=[[1, 2, 1], [2, 1, 7]]
mat=list(zip(*mat))
mat

[(1, 2), (2, 1), (1, 7)]

In [33]:

def prod_vector(v1,v2):
    if len(v1) == len (v2):
        #print(v1)
        #print(v2)
        l=[v1[i]*v2[i] for i  in  range(len(v1))]
        return(sum(l))
    else:
        print('Unvalid Shape')
def matrix_shape(mat):
    w=len(mat)
    h=len(mat[0])
    print(f' W= {len(mat)}  ,H ={len(mat[0])}')
    return w,h

def get_columns_as_vector(mat):
    return list(zip(*mat))


def mat_prod(mat1,mat2):
    mat1_row,mat1_colu=matrix_shape(mat1)
    mat2_row,mat2_colu=matrix_shape(mat2)

    if mat1_colu==mat2_row:
        print('Valid Matrix Multiplication')
        l=[]
        for i in range(len(mat1)):
            row=[]
            for j in range(mat1_colu):
                row.append(prod_vector(mat1[i],get_columns_as_vector(mat2)[j]))
            l.append(row)
        return l
        





In [34]:
mat1=[[1,2,1],[2,1,7]]
mat2=[[1,3,1],[3,1,1],[2,1,7]]
mat_prod(mat1,mat2)


 W= 2  ,H =3
 W= 3  ,H =3
Valid Matrix Multiplication


[[9, 6, 10], [19, 14, 52]]

In [35]:
file=open('test.txt','w')
file.write('WELWWEWEWEWE')
file.close()

In [37]:
import os 
os.getcwd()

'd:\\AMIT AI\\Python\\Week1'

# 1.9 NUmpy

In [39]:
import numpy as np 
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(4,4)

array([[0.80692099, 0.16156228, 0.47097271, 0.8816631 ],
       [0.26151324, 0.11379164, 0.65187966, 0.19688582],
       [0.31903486, 0.74477526, 0.8841731 , 0.48926612],
       [0.44477929, 0.84219099, 0.20127154, 0.56746755]])

In [46]:
np.random.randn(4) # gives random negative number with postive one (float)

array([ 0.04122152,  0.01499529, -0.56956053,  1.75271061])

In [45]:
np.random.rand(4)# --> float random

array([0.31827584, 0.68741165, 0.14586328, 0.78669671])

In [47]:
np.random.randint(5,10,4) # start ,end, number of output

array([7, 7, 5, 9])

In [50]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
mat[:3,2:3]  ## mat[row,columns]

array([[3],
       [6],
       [9]])

In [71]:
#create array of random int matrix
arr=np.random.randint(5,9,size=(3,4))

In [75]:
np.empty((3,3)) # can create a mtarix , that can be used to hold value to save memory 

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.13430793e-321],
       [6.23037317e-307, 8.91238232e-313, 9.55688114e-312]])

In [81]:
# vertstack vs hstack

arr1=np.array([1,3,4])
arr2=np.array([1,3,4])

print(f'Horizntal Stack = \n {np.hstack((arr1,arr2))} \n')
print(f'Vertical Stack = \n {np.vstack((arr1,arr2))}')



Horizntal Stack = 
 [1 3 4 1 3 4] 

Vertical Stack = 
 [[1 3 4]
 [1 3 4]]


In [116]:
data=np.array([['j',20,1],['k',60,0],['p',27,0],['m',20,1],['k',90,0],['u',100,0],['m',20,1],['h',90,0],['o',100,0]])

In [117]:
def train_split(data,prec):
    x=data[:,:2]
    y=data[:,-1]
    index=int(prec*len(data))
    

    return x[:index+1,:],y[:index+1],x[index+1:,:],y[index+1:]


In [131]:
y=data[:,-1]

In [126]:
data=np.array([['j',20,1],['k',60,0],['p',27,0],['m',20,1],['k',90,0],['u',100,0],['m',20,1],['h',90,0],['o',100,0]])
x_train,y_train,x_test,y_test=train_split(data,0.7)
x_train

array([['j', '20'],
       ['k', '60'],
       ['p', '27'],
       ['m', '20'],
       ['k', '90'],
       ['u', '100'],
       ['m', '20']], dtype='<U3')

In [139]:
np.array([[1,2,4]]).shape

(1, 3)

In [127]:
y_train

array(['1', '0', '0', '1', '0', '0', '1'], dtype='<U3')

In [128]:
x_test

array([['h', '90'],
       ['o', '100']], dtype='<U3')

In [142]:
y_test

array(['0', '0'], dtype='<U3')

In [147]:
arr.reshape(3,4,1)

array([[[7],
        [6],
        [8],
        [5]],

       [[5],
        [6],
        [8],
        [5]],

       [[6],
        [8],
        [6],
        [8]]])

In [148]:
def reshape_column(data,l):
    if l =='row':
        return data.reshape(1,len(data))
    elif l=='col':
         return data.reshape(len(data),1)
data=np.array([11,22,33,44,55])




In [149]:
reshape_column(data,'col')

array([[11],
       [22],
       [33],
       [44],
       [55]])

In [150]:
reshape_column(data,'row')

array([[11, 22, 33, 44, 55]])

In [152]:
data.shape

(5,)

In [153]:
#corellation of data 
np.linalg.matrix_rank(np.array([1,3,5,7,9]))

1

In [155]:
np.linalg.matrix_rank(np.array([100,300],[500,700],[900,700]))

1

# Pandas Dataframes

In [157]:
import pandas as pd

In [169]:
# create pandas series 
label=[1,2,4,5]

pd.Series([1,2,4,5],index=['A','B','C','D']) # create coulmn 



A    1
B    2
C    4
D    5
dtype: int64

In [170]:
label={'a':1,'b':2,'l':4,'p':5}

data=pd.Series(label) # create column with index mapping
data

a    1
b    2
l    4
p    5
dtype: int64

In [165]:
data['p']

5

In [171]:
import pandas as pd

In [188]:
df=pd.DataFrame({'A':[1,1,2],'B':[np.nan,2,4],'C':[np.nan,4,5]})

df

A    B    C
0  1  NaN  NaN
1  1  2.0  4.0
2  2  4.0  5.0

In [189]:
df.dropna(axis=1) #axis 0 will drop rows  if 1 column will droped

A
0  1
1  1
2  2

In [186]:
df

A    B    C
0  1  NaN  NaN
1  1  2.0  4.0
2  2  4.0  5.0

In [190]:
df.fillna(value=np.mean(df,axis=1))

A    B    C
0  1  NaN  NaN
1  1  2.0  4.0
2  2  4.0  5.0

In [191]:
df=pd.DataFrame(data=np.random.randn(4,5),index='A B C D'.split(), columns='DAY YEAR MONTH SEMISTER SPRING'.split())

df

DAY      YEAR     MONTH  SEMISTER    SPRING
A  0.665142 -0.728855  2.355428 -0.236787 -0.595463
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074
C  1.105405  0.713086 -0.813084 -1.109755  0.391267
D -0.911974  0.025961  0.393921 -0.824715 -3.541431

In [192]:
df['SALARY']=df['YEAR']+df['SEMISTER']
df

DAY      YEAR     MONTH  SEMISTER    SPRING    SALARY
A  0.665142 -0.728855  2.355428 -0.236787 -0.595463 -0.965641
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074 -1.068378
C  1.105405  0.713086 -0.813084 -1.109755  0.391267 -0.396669
D -0.911974  0.025961  0.393921 -0.824715 -3.541431 -0.798754

In [193]:
df.drop('SALARY',axis=1)
df

DAY      YEAR     MONTH  SEMISTER    SPRING    SALARY
A  0.665142 -0.728855  2.355428 -0.236787 -0.595463 -0.965641
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074 -1.068378
C  1.105405  0.713086 -0.813084 -1.109755  0.391267 -0.396669
D -0.911974  0.025961  0.393921 -0.824715 -3.541431 -0.798754

In [194]:
df.drop('SALARY',axis=1,inplace=True)
df

DAY      YEAR     MONTH  SEMISTER    SPRING
A  0.665142 -0.728855  2.355428 -0.236787 -0.595463
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074
C  1.105405  0.713086 -0.813084 -1.109755  0.391267
D -0.911974  0.025961  0.393921 -0.824715 -3.541431

In [196]:
df.loc['A']=[00,0,0,0,0]

In [197]:
df

DAY      YEAR     MONTH  SEMISTER    SPRING
A  0.000000  0.000000  0.000000  0.000000  0.000000
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074
C  1.105405  0.713086 -0.813084 -1.109755  0.391267
D -0.911974  0.025961  0.393921 -0.824715 -3.541431

In [200]:
df.loc['B'] # take row index as strin or location 

DAY         0.592676
YEAR       -2.019362
MONTH      -0.288529
SEMISTER    0.950984
SPRING     -1.317074
Name: B, dtype: float64

In [199]:
df.iloc[0:3]

DAY      YEAR     MONTH  SEMISTER    SPRING
A  0.000000  0.000000  0.000000  0.000000  0.000000
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074
C  1.105405  0.713086 -0.813084 -1.109755  0.391267

In [203]:
df

DAY      YEAR     MONTH  SEMISTER    SPRING
A  0.000000  0.000000  0.000000  0.000000  0.000000
B  0.592676 -2.019362 -0.288529  0.950984 -1.317074
C  1.105405  0.713086 -0.813084 -1.109755  0.391267
D -0.911974  0.025961  0.393921 -0.824715 -3.541431

In [202]:
df.loc['D','SPRING'] # string of index row then col index

-3.5414308156972347

In [206]:
df.iloc[-1,4]# string of index row then col index

-3.5414308156972347

In [211]:
df.loc[['C','D'],['SEMISTER','SPRING']] #get value of 2 column and 2 rows 

SEMISTER    SPRING
C -1.109755  0.391267
D -0.824715 -3.541431

In [235]:
out=['A1','A1','A1','A1','A2','A2','A2','A2','A3']
inp=[0,1,2,3,4,5,6,7,8]

h=list(zip(out,inp))

df=pd.MultiIndex.from_tuples(h)

df

MultiIndex([('A1', 0),
            ('A1', 1),
            ('A1', 2),
            ('A1', 3),
            ('A2', 4),
            ('A2', 5),
            ('A2', 6),
            ('A2', 7),
            ('A3', 8)],
           )

In [237]:
data=pd.DataFrame(np.random.randn(9,2),index=df,columns=['M1','M2'])

In [238]:
data

M1        M2
A1 0  1.444457 -2.159260
   1 -0.803368 -0.008194
   2  0.696860  0.228489
   3 -0.793621 -0.798862
A2 4 -0.310232  0.847168
   5 -0.294559 -0.504799
   6  1.629376  0.599848
   7  0.884421 -1.505825
A3 8 -1.879188 -0.394715

In [240]:
data.loc['A1'].loc[1]

M1   -0.803368
M2   -0.008194
Name: 1, dtype: float64

In [223]:
data.loc['A1'].iloc[0]

M1   -0.908511
M2    1.105763
Name: 1, dtype: float64

In [227]:
data.index.names=['Group','Element'] #update the names of index columns 

In [228]:
data

M1        M2
Group Element                    
A1    1       -0.908511  1.105763
      2       -0.817220 -0.972823
      3       -0.618364  0.458353
      4        1.790956 -0.868988
A2    5        0.598487  1.023187
      6       -1.821890 -1.425892
      7       -0.812796 -0.864541
      8       -1.767901  1.867857

In [242]:
df=pd.read_csv("example (1).csv",sep=',')

In [243]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [245]:
df=pd.read_excel("D:\AMIT AI\Python\Week1\Excel_Sample (1).xlsx")

In [247]:
df.isnull().sum()

Unnamed: 0    0
a             0
b             0
c             0
d             0
dtype: int64

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4 non-null      int64
 1   a           4 non-null      int64
 2   b           4 non-null      int64
 3   c           4 non-null      int64
 4   d           4 non-null      int64
dtypes: int64(5)
memory usage: 288.0 bytes


In [248]:
df.describe()

Unnamed: 0          a          b          c          d
count    4.000000   4.000000   4.000000   4.000000   4.000000
mean     1.500000   6.000000   7.000000   8.000000   9.000000
std      1.290994   5.163978   5.163978   5.163978   5.163978
min      0.000000   0.000000   1.000000   2.000000   3.000000
25%      0.750000   3.000000   4.000000   5.000000   6.000000
50%      1.500000   6.000000   7.000000   8.000000   9.000000
75%      2.250000   9.000000  10.000000  11.000000  12.000000
max      3.000000  12.000000  13.000000  14.000000  15.000000